project/logger_App/logger/urls.py
from django.urls import path
from . import views

app_name = 'logger'

urlpatterns = [
    path('',views.index, name='index'),
    path('add_new_item/',views.ProductCreate.as_view(),name='add-new-item'),
    path('add_new_customer/',views.CustomerCreate.as_view(),name='add-new-customer'),
    path('Customers/',views.CustomerListView.as_view(),name='customer-list'),
    path('Sales/',views.SaleListView.as_view(),name='sales-list'),
    path('add_new_sale/',views.SaleCreate.as_view(),name='add-new-sale'),
    path('<slug:type>/',views.ProductListView.as_view(), name='product-list'),
    path('<slug:type>/backup/',views.backup_product_csv, name='backup_product_csv'),
    path('<slug:type>/<int:pk>/',views.ProductDetailView.as_view(), name='product-detail'),
    path('<slug:type>/<int:pk>/edit',views.ProductEditView.as_view(), name='product-update'),
    path('<slug:type>/<int:pk>/update/<slug:field>/',views.update_product_field, name='update-product-field'),
]

project/logger_App/logger_App/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logger/', include('logger.urls')),
    path('', RedirectView.as_view(url='/login')),
    path('login/', auth_views.LoginView.as_view(template_name = 'logger/page-signin.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view( next_page = '/login'), name='logout')
]

project/logger_App/logger/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from django.urls import reverse

# Create your models here.
class User(AbstractUser):

    is_staff = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)

    def __str__(self):
        return str(self.username)

class Customer(models.Model):

    account = models.OneToOneField(User, null = True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    e_mail = models.EmailField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    type = (('B2B', 'B2B'), ('Retail', 'Retail'),)
    customer_type = models.CharField(max_length=15, choices=type, null=True)
    telephone = models.CharField(max_length=10, null=True)
    vat_id = models.CharField(max_length=30, null=True)
    address = models.CharField(max_length=20,null=True)
    balance = models.PositiveIntegerField(default=0, null=True)

    def __str__(self):
        return str(self.first_name) + '|' + str(self.vat_id)

    def get_absolute_url(self):
        return reverse('logger:customer-list')

    def Sales(self):
        return ', '.join([ ('[' + 'product_name: '+ str(sale.product_name) + ']') for sale in self.sales.all() ])

    def Balance(self):
        sum = 0
        for product in self.products.all():
            if product.payed == False:
                sum = sum + product.cost
        self.balance = sum
        self.save()
        return sum

    def Products(self):
        return ', '.join([ ('[' + 'product_type: '+ str(product.product_type)
        + ' device_model: '+ str(product.device_model)
        + ' issue: '+ str(product.Repairs())
        + ']') for product in self.products.all() ])

class Sale(models.Model):
    customer = models.ForeignKey(Customer,related_name='sales',on_delete=models.CASCADE)
    product_name = models.CharField(max_length=40, null=True)
    supplier = models.CharField(max_length=40, null=True)
    serial_number = models.CharField(max_length=40,null=True)
    invoice_no = models.PositiveIntegerField(default=0, null=True)
    price = models.PositiveIntegerField(default=0, null=True)
    comments = models.CharField(max_length=50, null=True)
    sale_date = models.DateTimeField(auto_now_add=True)
    warranty = models.CharField(max_length=20, null=True)

    def __str__(self):
        return str(self.customer.account.username) +'|' + str(self.product_name)

    def get_absolute_url(self):
        return reverse('logger:sales-list')


class Repair(models.Model):

    name = models.CharField(max_length=40, null=True)
    warranty = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    customer = models.ForeignKey(Customer,related_name='products',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    type = (('Notebook', 'Notebook'), ('Smartphone', 'Smartphone'),('Tablet', 'Tablet'),('Other', 'Other'),)
    product_type =  models.CharField(max_length=20, choices=type, null=True)
    device_model = models.CharField(max_length=40, null=True)
    serial_number = models.CharField(max_length=40,null=True)
    issue = models.ManyToManyField(Repair)
    damage_description = models.CharField(max_length=100,null=True)
    comment = models.CharField(max_length=100,null=True)
    cost = models.PositiveIntegerField(default=0, null=True)
    repaired = models.BooleanField(default=False)
    payed = models.BooleanField(default=False)
    canceled = models.BooleanField(default=False)

    def __str__(self):
        return str(self.customer.account.username) +' | ' + str(self.product_type) +' | ' + str(self.device_model) +' | ' + str(self.damage_description)

    def Repairs(self):
        return ', '.join([ (repair.name) for repair in self.issue.all() ])

    def Warranty(self):
        return ', '.join([ str(repair.name)+'|'+str(repair.warranty) for repair in self.issue.all() ])

    def get_absolute_url(self):
        return reverse('logger:product-detail' , kwargs ={ 'type':self.product_type,'pk': self.pk})

project/logger_App/logger/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User



class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username','password']

project/logger_App/logger/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.models import User
from .models import User,Customer,Product,Sale,Repair
from datetime import datetime, timedelta, time
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView
#Login required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.urls import reverse
from django.http import HttpResponseRedirect
import csv
# Create your views here.


#View for main app
@login_required
def index(request):

    '''
    Retrive index view
    '''

    #check if request user is Authenticated
    if request.user.is_superuser:
        return HttpResponseRedirect('/admin')
    elif request.user.is_staff:
        notebook_today = 0
        notebook_week = 0
        notebook_month = 0
        notebook_stats = []
        today = datetime.now().date()
        customer_unrepaired_notebooks = Product.objects.none
        #Retrive Notebooks
        if Product.objects.filter(product_type='Notebook').exists():
            customer_notebooks = Product.objects.filter(product_type='Notebook')
            number_of_notebooks = len(customer_notebooks)

            for notebook in customer_notebooks:
                if notebook.created_at.day == today.day:
                    notebook_today=notebook_today+1
                if notebook.created_at.isocalendar()[1] is today.isocalendar()[1]:
                    notebook_week= notebook_week+1
                if notebook.created_at.month is today.month:
                    notebook_month = notebook_month +1

            notebook_stats.append(notebook_today)
            notebook_stats.append(notebook_week)
            notebook_stats.append(notebook_month)
            #Retrive Unrepaired Notebooks
            if Product.objects.filter(product_type='Notebook',repaired=False).exists():
                customer_unrepaired_notebooks = Product.objects.filter(product_type='Notebook',repaired=False)
                notebook_percentage = int((1 - len(customer_unrepaired_notebooks)/number_of_notebooks)*100)
            else:
                customer_unrepaired_notebooks = Product.objects.none
                notebook_percentage=int(100)
        else:
            notebook_stats.append(notebook_today)
            notebook_stats.append(notebook_week)
            notebook_stats.append(notebook_month)
            notebook_percentage=int(0)

        smartphone_today = 0
        smartphone_week = 0
        smartphone_month = 0
        smartphone_stats = []
        customer_unrepaired_smartphones = Product.objects.none
        #Retrive Smartphones
        if Product.objects.filter(product_type='Smartphone').exists():
            customer_smartphones = Product.objects.filter(product_type='Smartphone')
            number_of_smartphones = len(customer_smartphones)

            for smartphone in customer_smartphones:
                if smartphone.created_at.day == today.day:
                    smartphone_today=smartphone_today+1
                if smartphone.created_at.isocalendar()[1] is today.isocalendar()[1]:
                    smartphone_week= smartphone_week+1
                if smartphone.created_at.month is today.month:
                    smartphone_month = smartphone_month +1

            smartphone_stats.append(smartphone_today)
            smartphone_stats.append(smartphone_week)
            smartphone_stats.append(smartphone_month)
            #Retrive Unrepaired Notebooks
            if Product.objects.filter(product_type='Smartphone',repaired=False).exists():
                customer_unrepaired_smartphones = Product.objects.filter(product_type='Smartphone',repaired=False)
                smartphone_percentage = int((1 - len(customer_unrepaired_smartphones)/number_of_smartphones)*100)
            else:
                customer_unrepaired_smartphones = Product.objects.none
                smartphone_percentage=int(100)

        else:
            smartphone_stats.append(smartphone_today)
            smartphone_stats.append(smartphone_week)
            smartphone_stats.append(smartphone_month)
            smartphone_percentage=int(0)

        tablet_today = 0
        tablet_week = 0
        tablet_month = 0
        tablet_stats = []
        customer_unrepaired_tablets = Product.objects.none
        #Retrive Tablets
        if Product.objects.filter(product_type='Tablet').exists():
            customer_tablets = Product.objects.filter(product_type='Tablet')


            number_of_tablet = len(customer_tablets)

            for tablet in customer_tablets:
                if tablet.created_at.day == today.day:
                    tablet_today=tablet_today+1
                if tablet.created_at.isocalendar()[1] is today.isocalendar()[1]:
                    tablet_week= tablet_week+1
                if tablet.created_at.month is today.month:
                    tablet_month = tablet_month +1

            tablet_stats.append(tablet_today)
            tablet_stats.append(tablet_week)
            tablet_stats.append(tablet_month)

            #Retrive Unrepaired Tablets
            if Product.objects.filter(product_type='Tablet',repaired=False).exists():
                customer_unrepaired_tablets = Product.objects.filter(product_type='Tablet',repaired=False)
                tablet_percentage = int((1 - len(customer_unrepaired_tablets)/number_of_tablet)*100)
            else:
                customer_unrepaired_tablets = Product.objects.none
                tablet_percentage=int(100)


        else:
            tablet_stats.append(tablet_today)
            tablet_stats.append(tablet_week)
            tablet_stats.append(tablet_month)
            tablet_percentage=int(0)



    elif request.user.is_customer:

        user = User.objects.get(username=request.user)
        customer = Customer.objects.get(account=user)
        customer_unrepaired_notebooks = Product.objects.none
        notebook_today = 0
        notebook_week = 0
        notebook_month = 0
        notebook_stats = []
        today = datetime.now().date()
        #Retrive Notebooks
        if Product.objects.filter(customer =customer,product_type='Notebook').exists():
            customer_notebooks = Product.objects.filter(customer =customer,product_type='Notebook')
            number_of_notebooks = len(customer_notebooks)

            for notebook in customer_notebooks:
                if notebook.created_at.day == today.day:
                    notebook_today=notebook_today+1
                if notebook.created_at.isocalendar()[1] is today.isocalendar()[1]:
                    notebook_week= notebook_week+1
                if notebook.created_at.month is today.month:
                    notebook_month = notebook_month +1

            notebook_stats.append(notebook_today)
            notebook_stats.append(notebook_week)
            notebook_stats.append(notebook_month)
            #Retrive Unrepaired Notebooks
            if Product.objects.filter(customer =customer,product_type='Notebook',repaired=False).exists():
                customer_unrepaired_notebooks = Product.objects.filter(customer =customer,product_type='Notebook',repaired=False)
                notebook_percentage = int((1 - len(customer_unrepaired_notebooks)/number_of_notebooks)*100)
            else:
                customer_unrepaired_notebooks = Product.objects.none
                notebook_percentage=int(100)
        else:
            notebook_stats.append(notebook_today)
            notebook_stats.append(notebook_week)
            notebook_stats.append(notebook_month)
            notebook_percentage=int(0)

        smartphone_today = 0
        smartphone_week = 0
        smartphone_month = 0
        smartphone_stats = []
        customer_unrepaired_smartphones = Product.objects.none
        #Retrive Smartphones
        if Product.objects.filter(customer =customer,product_type='Smartphone').exists():
            customer_smartphones = Product.objects.filter(customer =customer,product_type='Smartphone')
            number_of_smartphones = len(customer_smartphones)

            for smartphone in customer_smartphones:
                if smartphone.created_at.day == today.day:
                    smartphone_today=smartphone_today+1
                if smartphone.created_at.isocalendar()[1] is today.isocalendar()[1]:
                    smartphone_week= smartphone_week+1
                if smartphone.created_at.month is today.month:
                    smartphone_month = smartphone_month +1

            smartphone_stats.append(smartphone_today)
            smartphone_stats.append(smartphone_week)
            smartphone_stats.append(smartphone_month)
            #Retrive Unrepaired Notebooks
            if Product.objects.filter(customer =customer,product_type='Smartphone',repaired=False).exists():
                customer_unrepaired_smartphones = Product.objects.filter(customer =customer,product_type='Smartphone',repaired=False)
                smartphone_percentage = int((1 - len(customer_unrepaired_smartphones)/number_of_smartphones)*100)
            else:
                customer_unrepaired_smartphones = Product.objects.none
                smartphone_percentage=int(100)

        else:
            smartphone_stats.append(smartphone_today)
            smartphone_stats.append(smartphone_week)
            smartphone_stats.append(smartphone_month)
            smartphone_percentage=int(0)

        tablet_today = 0
        tablet_week = 0
        tablet_month = 0
        tablet_stats = []
        customer_unrepaired_tablets = Product.objects.none
        #Retrive Tablets
        if Product.objects.filter(customer =customer,product_type='Tablet').exists():
            customer_tablets = Product.objects.filter(customer =customer,product_type='Tablet')

project/logger_App/logger/templates/logger/customers.html
{% extends 'logger/base.html' %}

{%block body %}
    <div class="kt-breadcrumb">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" href="index.html">Dashboard</a>
        <span class="breadcrumb-item active">Customers</span>
      </nav>
    </div><!-- kt-breadcrumb -->

    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      <div class="kt-pagetitle">
        <h5>Customers</h5>
      </div><!-- kt-pagetitle -->

      <div class="kt-pagebody">
        <div class="row row-sm">
          <div class="col-lg-12">
            <div class="card pd-20 pd-sm-40">
              <h6 class="card-body-title">Customers</h6>
              <p class="mg-b-20 mg-sm-b-30">Searching customers</p>
              <div class="d-flex">
                 <a href="{% url 'logger:add-new-customer' %}" class="btn btn-info bd-0 pd-x-20"><i class="fa fa-plus mg-r-5"></i>Add New</a>
               </div><!-- d-flex -->
              <div class="table-wrapper mg-t-20">
                <table id="customers" class="table display responsive nowrap">
                  <thead>
                    <tr>
                      <th class="wd-15p">First_name</th>
                      <th class="wd-15p">Last_name</th>
                      <th class="wd-20p">Customer Type</th>
                      <th class="wd-20p">Vat Id</th>
                      <th class="wd-15p">Address</th>
                      <th class="wd-12p">Telephone</th>
                      <th class="wd-15p">E-mail</th>
                      <th class="wd-10p">Pending Payments</th>
                    </tr>
                  </thead>
                  <tbody>
                    {%for object in object_list %}
                    <tr>
                      <td>{{object.first_name}}</td>
                      <td>{{object.last_name}}</td>
                      <td>{{object.customer_type}}</td>
                      <td>{{object.vat_id}}</td>
                      <td>{{object.address}}</td>
                      <td>{{object.telephone}}</td>
                      <td>{{object.e_mail}}</td>
                      <td>{{object.Balance}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div><!-- table-wrapper -->
            </div><!-- card -->
        </div><!-- col-12 -->
      </div><!-- row -->
      </div><!-- kt-pagebody -->
    </div><!-- kt-mainpanel -->

    {%endblock%}

    {%block scripts %}

    <script>
      $(function(){
        'use strict';

        $('#customers').DataTable({
          responsive: true,
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          }
        });

      });


    </script>

  {%endblock%}

project/logger_App/logger/templates/logger/object_detail.html
{% extends 'logger/base.html' %}

{%block body %}
   {% load static %}
    <div class="kt-breadcrumb">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" href="index.html">Dashboard</a>
        <span class="breadcrumb-item active">{{type}} #{{object.id}}</span>
      </nav>
    </div><!-- kt-breadcrumb -->

    <!-- ##### MAIN PANEL ##### -->
    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      <div class="kt-pagetitle">
        <h5>{{type}} #{{object.id}}</h5>
      </div><!-- kt-pagetitle -->

      <div class="kt-pagebody">
        <div class="row row-sm">
            <div class="col-lg-12">
              <div class="card bd-gray-300">
                <div class="card-header bg-gray-100 pd-y-15 pd-x-20">
                  <h6 class="card-title tx-uppercase tx-12 mg-b-0">{{type}} #{{object.id}} Details</h6>
                </div><!-- card-header -->
                <div class="table-responsive">
                  <table class="table table-white mg-b-0 tx-12">
                    <tbody>
                      <tr>
                        <td class="pd-l-20 tx-center">
                          <img src="{% static 'logger/img/conn.svg' %}" class="wd-36 rounded-circle" alt="Image">
                        </td>
                        <td>
                          <a href="" class="tx-inverse tx-14 tx-medium d-block">{{object.customer.first_name}} {{object.customer.last_name}}</a>
                          <span class="tx-11 d-block">Phone: {{object.customer.telephone}}</span>
                        </td>
                        <td class="tx-12">
                          {% if object.repaired is True %}
                          <span class="square-8 bg-success mg-r-5 rounded-circle"></span>Repaired
                          {% endif %}
                          {% if object.repaired is False %}
                          <span class="square-8 bg-danger mg-r-5 rounded-circle"></span>Unrepaired
                          {% endif %}
                        </td>
                        <td>{{object.created_at|date:"d-m-Y H:i"}}</td>
                      </tr>
                    </tbody>
                  </table>
                </div><!-- table-responsive -->
              </div><!-- card -->
            </div><!-- col-12 -->
          </div><!-- row -->
          <div class="row row-sm mg-t-20">
              <div class="col-lg-12">
                <div class="card pd-20 pd-sm-40">
                  <div class="table-wrapper mg-t-20">
                    <table id="{{type}}" class="table display responsive nowrap">
                      <thead>
                        <tr>
                          <th class="wd-15p">Device Model</th>
                          <th class="wd-15p">Serial Number</th>
                          <th class="wd-20p">Issue</th>
                          <th class="wd-20p">Comments</th>
                          <th class="wd-15p">Warranty</th>
                          <th class="wd-10p">Cost</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>{{object.device_model}}</td>
                          <td>{{object.serial_number}}</td>
                          <td>{{object.Repairs}}</td>
                          <td>{{object.comments}}</td>
                          <td>{{object.Warranty}}</td>
                          <td>{{object.cost}}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div><!-- table-wrapper -->
                </div><!-- card -->
            </div><!-- col-12 -->
          </div><!-- row -->
          {% if request.user.is_staff %}
          <div class="row row-sm mg-t-20">
             <div class="col-sm-3">
               <div class="card pd-40 tx-center">
                 <h6 class="tx-md-20 tx-inverse mg-b-20">Status</h6>
                  {% if object.repaired is True %}
                  <a href="{% url 'logger:update-product-field' type object.id 'repaired' %}" class="btn btn-success btn-block">Repaired</a>
                  {% endif %}
                  {% if object.repaired is False %}
                  <a href="{% url 'logger:update-product-field' type object.id 'repaired' %}" class="btn btn-danger btn-block">Unrepaired</a>
                  {% endif %}
               </div><!-- card -->
             </div><!-- col-4 -->
             <div class="col-sm-3 mg-t-20 mg-sm-t-0">
               <div class="card pd-40 tx-center">
                 <h6 class="tx-md-20 tx-inverse mg-b-20">Payment</h6>
                 {% if object.payed is True %}
                 <a href="{% url 'logger:update-product-field' type object.id 'payed' %}" class="btn btn-success btn-block">Paid</a>
                 {% endif %}
                 {% if object.payed is False %}
                 <a href="{% url 'logger:update-product-field' type object.id 'payed' %}" class="btn btn-danger btn-block">Unpaid</a>
                 {% endif %}
               </div><!-- card -->
             </div><!-- col-4 -->
             <div class="col-sm-3 mg-t-20 mg-sm-t-0">
               <div class="card pd-40 tx-center">
                 <h6 class="tx-md-20 tx-inverse mg-b-20">Canceled</h6>
                 {% if object.canceled is True %}
                 <a href="{% url 'logger:update-product-field' type object.id 'canceled' %}" class="btn btn-success btn-block">Yes</a>
                 {% endif %}
                 {% if object.canceled is False %}
                 <a href="{% url 'logger:update-product-field' type object.id 'canceled' %}" class="btn btn-danger btn-block">No</a>
                 {% endif %}
               </div><!-- card -->
             </div><!-- col-4 -->
             <div class="col-sm-3 mg-t-20 mg-sm-t-0">
               <div class="card pd-40 tx-center">
                 <h6 class="tx-md-20 tx-inverse mg-b-20">Customized</h6>
                 <a href="{% url 'logger:product-update' type object.id %}" class="btn btn-default btn-block">Edit</a>
               </div><!-- card -->
             </div><!-- col-4 -->
           </div><!-- row -->
           {%endif%}
      </div><!-- kt-pagebody -->
    </div><!-- kt-mainpanel -->

    {%endblock%}

    {%block scripts %}


    <script>
      $(function(){
        'use strict';

        $('#{{type}}').DataTable({
          bLengthChange: false,
          searching: false,
          responsive: true
        });


      });


    </script>
  {%endblock%}

project/logger_App/logger/templates/logger/object_list.html
{% extends 'logger/base.html' %}

{%block body %}
    <div class="kt-breadcrumb">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" href="index.html">Dashboard</a>
        <span class="breadcrumb-item active">{{type}}</span>
      </nav>
    </div><!-- kt-breadcrumb -->

    <!-- ##### MAIN PANEL ##### -->
    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      <div class="kt-pagetitle">
        <h5>{{type}}</h5>
      </div><!-- kt-pagetitle -->

      <div class="kt-pagebody">
        <div class="row row-sm">
            <div class="col-lg-12">
              <div class="card pd-20 pd-sm-40">
                <h6 class="card-body-title">{{type}}</h6>
                <p class="mg-b-20 mg-sm-b-30">Searching {{type}}</p>
                <div class="d-flex">
                   {% if request.user.is_staff %}
                   <a href="{% url 'logger:add-new-item' %}" class="btn btn-info bd-0 pd-x-20"><i class="fa fa-plus mg-r-5"></i>Add New</a>
                   {% endif %}
                   <a href="{% url 'logger:backup_product_csv' type %}" class="btn btn-success bd-0 pd-x-20 mg-l-auto"><i class="fa fa-download mg-r-5"></i>Download Data</a>
                 </div><!-- d-flex -->
                <div class="table-wrapper mg-t-20">
                  <table id="{{type}}" class="table display responsive nowrap">
                    <thead>
                      <tr>
                        <th class="wd-10p">Id</th>
                        <th class="wd-15p">Date</th>
                        <th class="wd-15p">Name</th>
                        <th class="wd-20p">Device Model</th>
                        <th class="wd-20p">Serial Number</th>
                        <th class="wd-20p">Issue</th>
                        <th class="wd-10p">Cost</th>
                      </tr>
                    </thead>
                    <tbody>
                      {%for object in object_list %}
                      <tr>
                        <td><a href="{% url 'logger:product-detail' type object.id %}">{{object.id}}</a></td>
                        <td>{{object.created_at|date:"d-m-Y H:i"}}</td>
                        <td>{{object.customer.first_name}} {{object.customer.last_name}}</td>
                        <td>{{object.device_model}}</td>
                        <td>{{object.serial_number}}</td>
                        <td>{{object.Repairs}}</td>
                        <td>{{object.cost}}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div><!-- table-wrapper -->
              </div><!-- card -->
          </div><!-- col-12 -->
        </div><!-- row -->
      </div><!-- kt-pagebody -->
    </div><!-- kt-mainpanel -->

    {%endblock%}

    {%block scripts %}

    <script>
      $(function(){
        'use strict';

        $('#{{type}}').DataTable({
          responsive: true,
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          }
        });

      });


    </script>

    {%endblock%}

project/logger_App/logger/templates/logger/sales.html
{% extends 'logger/base.html' %}

{%block body %}
    <div class="kt-breadcrumb">
      <nav class="breadcrumb">
        <a class="breadcrumb-item" href="index.html">Dashboard</a>
        <span class="breadcrumb-item active">Sales</span>
      </nav>
    </div><!-- kt-breadcrumb -->

    <!-- ##### MAIN PANEL ##### -->
    <div class="kt-mainpanel">
      <div class="kt-pagetitle">
        <h5>Sales</h5>
      </div><!-- kt-pagetitle -->

      <div class="kt-pagebody">
        <div class="row row-sm">
          <div class="col-lg-12">
            <div class="card pd-20 pd-sm-40">
              <h6 class="card-body-title">Sales</h6>
              <p class="mg-b-20 mg-sm-b-30">Searching sales</p>
              <div class="d-flex">
                 <a href="{% url 'logger:add-new-sale' %}" class="btn btn-info bd-0 pd-x-20"><i class="fa fa-plus mg-r-5"></i>Add New</a>
               </div><!-- d-flex -->
              <div class="table-wrapper mg-t-20">
                <table id="sales" class="table display responsive nowrap">
                  <thead>
                    <tr>
                      <th class="wd-15p">Name</th>
                      <th class="wd-20p">Customer Type</th>
                      <th class="wd-20p">Product Name</th>
                      <th class="wd-15p">Supplier</th>
                      <th class="wd-12p">Serial Number</th>
                      <th class="wd-15p">Invoice_no</th>
                      <th class="wd-10p">Price</th>
                      <th class="wd-10p">Comments</th>
                      <th class="wd-10p">Date</th>
                      <th class="wd-10p">Warranty</th>
                    </tr>
                  </thead>
                  <tbody>
                    {%for object in object_list %}
                    <tr>
                      <td>{{object.customer.first_name}} {{object.customer.last_name}}</td>
                      <td>{{object.customer.customer_type}}</td>
                      <td>{{object.product_name}}</td>
                      <td>{{object.supplier}}</td>
                      <td>{{object.serial_number}}</td>
                      <td>{{object.invoice_no}}</td>
                      <td>{{object.price}}</td>
                      <td>{{object.comments}}</td>
                      <td>{{object.sale_date|date:"d-m-Y H:i"}}</td>
                      <td>{{object.warranty}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div><!-- table-wrapper -->
            </div><!-- card -->
        </div><!-- col-12 -->
      </div><!-- row -->
      </div><!-- kt-pagebody -->
    </div><!-- kt-mainpanel -->

    {%endblock%}

    {%block scripts %}

    <script>
      $(function(){
        'use strict';

        $('#sales').DataTable({
          responsive: true,
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          }
        });

      });


    </script>

  {%endblock%}